-- Pearls Aesthetic Clinic Library
-- 0022: Import the live treatment/procedure catalogue.
--
-- Source captured on 2026-08-21:
-- https://pearls-demo-one.vercel.app/
--
-- The live menu contains 263 entries. Eight FAQ-only links are intentionally
-- excluded and twelve repeated cross-division labels are de-duplicated by the
-- same normalized-key rule used by the application, leaving 243 procedures.
-- Existing rows and case references are preserved.

begin;

do $$
declare
  v_admin uuid;
  v_existing_count integer;
begin
  select p.id into v_admin
  from public.profiles p
  join public.roles r on r.id = p.role_id
  where r.code = 'ADMIN' and p.is_active
  order by case when p.display_name = 'Clinic Admin' then 0 else 1 end, p.created_at
  limit 1;

  with source(display_name, sort_order) as (
    values
    ('Rhinoplasty (Nose Job)', 1),
    ('Tip Rhinoplasty (Tip Plasty)', 2),
    ('Alar Base Reduction', 3),
    ('Ethnic Rhinoplasty', 4),
    ('Ultrasonic Rhinoplasty', 5),
    ('Preservation Rhinoplasty', 6),
    ('Male Rhinoplasty', 7),
    ('Septoplasty', 8),
    ('Turbinate Reduction', 9),
    ('Septorhinoplasty', 10),
    ('Revision Rhinoplasty', 11),
    ('Nose Thread Lift', 12),
    ('Breast Augmentation with Implants', 13),
    ('Mini Breast Augmentation', 14),
    ('Breast Implant Options', 15),
    ('Fat Transfer Breast Augmentation', 16),
    ('Hybrid Breast Augmentation', 17),
    ('Breast Implant Check', 18),
    ('Breast Implant Removal (Explant)', 19),
    ('Implant Removal with Breast Lift', 20),
    ('Breast Implant Replacement', 21),
    ('Breast Implant Revision', 22),
    ('Breast Lift (Mastopexy)', 23),
    ('Breast Lift with Implants', 24),
    ('Breast Lift with Auto-Augmentation', 25),
    ('Mini Breast Lift (Doughnut Mastopexy)', 26),
    ('Breast Reduction', 27),
    ('Liposuction Breast Reduction', 28),
    ('Inverted Nipple Correction', 29),
    ('Nipple Reduction', 30),
    ('Areola Reduction', 31),
    ('Breast Asymmetry Correction', 32),
    ('Tuberous Breast Correction', 33),
    ('Mommy Makeover', 34),
    ('Breast Lift or Augmentation', 35),
    ('Tummy Tuck with Muscle Repair', 36),
    ('Liposuction / 360 Lipo', 37),
    ('Labiaplasty or Vaginoplasty', 38),
    ('Facelift (Rhytidectomy)', 39),
    ('SMAS Facelift', 40),
    ('Deep Plane Facelift', 41),
    ('Upper Facelift (Forehead Lift)', 42),
    ('Mid-Facelift (Cheek Lift)', 43),
    ('Lower Facelift (Jowl Lift)', 44),
    ('Mini Facelift', 45),
    ('One-Stitch Facelift', 46),
    ('Male Facelift', 47),
    ('Neck Lift', 48),
    ('Mini Neck Lift', 49),
    ('Male Neck Lift', 50),
    ('Chin & Neck Liposuction', 51),
    ('FaceTite', 52),
    ('Facial Fat Transfer', 53),
    ('Lip Lift', 54),
    ('Lip Reduction Surgery', 55),
    ('Buccal Fat Removal', 56),
    ('Dimple Creation', 57),
    ('Chin Surgery (Genioplasty)', 58),
    ('Chin Augmentation', 59),
    ('Chin Reduction', 60),
    ('Male Chin Surgery', 61),
    ('Liposuction', 62),
    ('Stomach Liposuction', 63),
    ('360 Liposuction', 64),
    ('Micro Liposuction (MicroLipo)', 65),
    ('High Definition Liposuction', 66),
    ('Abdominal Etching', 67),
    ('Male Liposuction', 68),
    ('BodyTite', 69),
    ('Cellulite Treatment', 70),
    ('Tummy Tuck (Abdominoplasty)', 71),
    ('Brazilian Tummy Tuck', 72),
    ('Mini Tummy Tuck', 73),
    ('Male Tummy Tuck', 74),
    ('Umbilicoplasty', 75),
    ('Mons Lift (Monsplasty)', 76),
    ('C-Section Scar Revision', 77),
    ('Body Contouring Procedures', 78),
    ('Fat Transfer (Fat Grafting)', 79),
    ('Pectoral Implants', 80),
    ('Chest Wall Implants', 81),
    ('Calf Augmentation with Implants', 82),
    ('Fat Transfer Calf Augmentation', 83),
    ('Brazilian Butt Lift (BBL)', 84),
    ('Ultrasound Guided BBL', 85),
    ('Skinny BBL', 86),
    ('Mini BBL', 87),
    ('360 Lipo and BBL', 88),
    ('Revision BBL', 89),
    ('Male BBL', 90),
    ('BBL Recovery Guide', 91),
    ('BBL Before & After', 92),
    ('Buttock Implants', 93),
    ('Butt Implant Removal', 94),
    ('Butt Implants vs BBL', 95),
    ('Non-Surgical Butt Lift (HyaCorp)', 96),
    ('Labiaplasty (Labia Reduction)', 97),
    ('Clitoral Hood Reduction', 98),
    ('Labiaplasty Revision', 99),
    ('Labia Puffing (Labial Puff)', 100),
    ('Vaginoplasty (Vaginal Tightening)', 101),
    ('Perineoplasty', 102),
    ('Pelvic Floor Repair', 103),
    ('Vaginal Rejuvenation', 104),
    ('IntimaLase Vaginal Tightening', 105),
    ('IncontiLase Urinary Incontinence', 106),
    ('ProlapLase Pelvic Prolapse', 107),
    ('RenovaLase Vaginal Dryness', 108),
    ('Non-Surgical Vaginal Tightening', 109),
    ('O-Shot Injection', 110),
    ('G-Spot Injection (G-Shot)', 111),
    ('Gynecomastia Surgery', 112),
    ('Male Breast Reduction', 113),
    ('Male Eyelid Surgery', 114),
    ('Male Body Lift', 115),
    ('Fotona 4D Laser Facelift', 116),
    ('SmoothEye Laser Treatment', 117),
    ('LipLase Lip Laser Treatment', 118),
    ('Erbium Laser Skin Resurfacing', 119),
    ('Laser TightSculpting', 120),
    ('Laser Skin Tightening', 121),
    ('Laser Acne Treatment', 122),
    ('Rosacea Laser Treatment', 123),
    ('Laser Cellulite Treatment', 124),
    ('Facial Thread Vein Removal', 125),
    ('Nose Thread Vein Removal', 126),
    ('Periorbital Vein Laser Treatment', 127),
    ('Veins Under the Eyes', 128),
    ('Venous Lake Removal', 129),
    ('Cherry Angioma Removal', 130),
    ('Laser Pigmentation Treatment', 131),
    ('Melasma Laser Treatment', 132),
    ('Age Spot Removal', 133),
    ('Laser Mole Removal', 134),
    ('Xanthelasma Removal', 135),
    ('Sebaceous Hyperplasia Removal', 136),
    ('Syringoma Removal', 137),
    ('Milia Removal', 138),
    ('Wart Removal', 139),
    ('Verruca Removal', 140),
    ('Seborrhoeic Keratosis Removal', 141),
    ('Dermatosis Papulosa Nigra Removal', 142),
    ('Actinic Keratosis Treatment', 143),
    ('Laser Scar Removal', 144),
    ('LineLase Stretch Mark Removal', 145),
    ('Laser Fungal Nail Treatment', 146),
    ('NightLase Snoring Treatment', 147),
    ('Vaginal Laser Treatment', 148),
    ('Laser Intimate Whitening', 149),
    ('Anti-Wrinkle Injections', 150),
    ('Frown Lines', 151),
    ('Forehead Wrinkles', 152),
    ('Crow''s Feet', 153),
    ('Bunny Lines', 154),
    ('Lip Flip', 155),
    ('Gummy Smile', 156),
    ('Jaw Slimming Injections', 157),
    ('Anti-Sweat Injections', 158),
    ('Muscle Relaxant for Migraine', 159),
    ('Dermal Fillers', 160),
    ('Facial Fillers', 161),
    ('Lip Fillers', 162),
    ('Cheek Fillers', 163),
    ('Nasolabial Folds', 164),
    ('Marionette Lines', 165),
    ('Chin Fillers', 166),
    ('Jawline Fillers', 167),
    ('Temple Filler', 168),
    ('Tear Trough Filler', 169),
    ('Non-Surgical Rhinoplasty', 170),
    ('Liquid Facelift (8-Point Lift)', 171),
    ('Filler Dissolving Treatment', 172),
    ('Morpheus8 RF Microneedling', 173),
    ('Skin Boosters', 174),
    ('Profhilo Treatment', 175),
    ('Thread Lift', 176),
    ('Double Chin Injections', 177),
    ('Skin Lesion Removal', 178),
    ('Facial Skin Lesion Removal', 179),
    ('Lip Lesion Removal', 180),
    ('Skin Tag Removal', 181),
    ('Mole Removal Surgery', 182),
    ('Cyst Removal Surgery', 183),
    ('Lipoma Removal Surgery', 184),
    ('Dermatofibroma Removal', 185),
    ('Pyogenic Granuloma Removal', 186),
    ('Osteoma Removal', 187),
    ('Rhinophyma Surgery', 188),
    ('Skin Cancer Surgery', 189),
    ('Scar Revision Surgery', 190),
    ('Facial Scar Revision', 191),
    ('Acne Scar Removal', 192),
    ('Hypertrophic Scar Treatment', 193),
    ('Keloid Scar Treatment', 194),
    ('Burn Scars Treatment', 195),
    ('Surgical Tattoo Removal', 196),
    ('Micro & Nano Fat Grafting', 197),
    ('Subcision for Cellulite', 198),
    ('Suction Curettage for Hyperhidrosis', 199),
    ('Blepharoplasty (Eyelid Surgery)', 200),
    ('Upper Eyelid Surgery', 201),
    ('Lower Eyelid Surgery', 202),
    ('Asian Blepharoplasty', 203),
    ('Canthoplasty (Almond Eye Surgery)', 204),
    ('Revision Blepharoplasty', 205),
    ('Brow Lift (Forehead Lift)', 206),
    ('Endoscopic Brow Lift', 207),
    ('Temporal Brow Lift', 208),
    ('Brow Lift vs Blepharoplasty', 209),
    ('Hairline Lowering', 210),
    ('AccuTite', 211),
    ('Otoplasty (Ear Pinning)', 212),
    ('Earlobe Repair', 213),
    ('Earlobe Reduction', 214),
    ('Body Contouring After Weight Loss', 215),
    ('Excess Skin Removal Surgery', 216),
    ('Extended Tummy Tuck', 217),
    ('Fleur-de-Lis Tummy Tuck', 218),
    ('Apronectomy (Panniculectomy)', 219),
    ('Arm Lift (Brachioplasty)', 220),
    ('Thigh Lift (Thigh Reduction)', 221),
    ('Lower Back Lift', 222),
    ('Bra Line Back Lift', 223),
    ('Buttock Lift (Gluteal Lift)', 224),
    ('Upper Body Lift', 225),
    ('Lower Body Lift', 226),
    ('Belt Lipectomy', 227),
    ('FtM / FtN Top Surgery', 228),
    ('Double Incision Top Surgery', 229),
    ('Keyhole Top Surgery', 230),
    ('MtF Top Surgery', 231),
    ('Facial Feminisation Surgery (FFS)', 232),
    ('Tracheal Shave', 233),
    ('Body Masculinisation Surgery', 234),
    ('Gender Affirmation Surgery', 235),
    ('WPATH Letter for Top Surgery', 236),
    ('FUE Hair Transplant', 237),
    ('Hairline Design & Lowering', 238),
    ('Crown & Vertex Restoration', 239),
    ('Beard Transplant', 240),
    ('Eyebrow Transplant', 241),
    ('Scar Hair Transplant', 242),
    ('PRP Hair Therapy', 243)
  ),
  normalized as (
    select
      public.normalize_master_key(display_name) as normalized_key,
      public.normalize_master_display(display_name) as display_name,
      sort_order
    from source
  )
  select count(*) into v_existing_count
  from normalized n
  join public.procedures p using (normalized_key);

  with source(display_name, sort_order) as (
    values
    ('Rhinoplasty (Nose Job)', 1),
    ('Tip Rhinoplasty (Tip Plasty)', 2),
    ('Alar Base Reduction', 3),
    ('Ethnic Rhinoplasty', 4),
    ('Ultrasonic Rhinoplasty', 5),
    ('Preservation Rhinoplasty', 6),
    ('Male Rhinoplasty', 7),
    ('Septoplasty', 8),
    ('Turbinate Reduction', 9),
    ('Septorhinoplasty', 10),
    ('Revision Rhinoplasty', 11),
    ('Nose Thread Lift', 12),
    ('Breast Augmentation with Implants', 13),
    ('Mini Breast Augmentation', 14),
    ('Breast Implant Options', 15),
    ('Fat Transfer Breast Augmentation', 16),
    ('Hybrid Breast Augmentation', 17),
    ('Breast Implant Check', 18),
    ('Breast Implant Removal (Explant)', 19),
    ('Implant Removal with Breast Lift', 20),
    ('Breast Implant Replacement', 21),
    ('Breast Implant Revision', 22),
    ('Breast Lift (Mastopexy)', 23),
    ('Breast Lift with Implants', 24),
    ('Breast Lift with Auto-Augmentation', 25),
    ('Mini Breast Lift (Doughnut Mastopexy)', 26),
    ('Breast Reduction', 27),
    ('Liposuction Breast Reduction', 28),
    ('Inverted Nipple Correction', 29),
    ('Nipple Reduction', 30),
    ('Areola Reduction', 31),
    ('Breast Asymmetry Correction', 32),
    ('Tuberous Breast Correction', 33),
    ('Mommy Makeover', 34),
    ('Breast Lift or Augmentation', 35),
    ('Tummy Tuck with Muscle Repair', 36),
    ('Liposuction / 360 Lipo', 37),
    ('Labiaplasty or Vaginoplasty', 38),
    ('Facelift (Rhytidectomy)', 39),
    ('SMAS Facelift', 40),
    ('Deep Plane Facelift', 41),
    ('Upper Facelift (Forehead Lift)', 42),
    ('Mid-Facelift (Cheek Lift)', 43),
    ('Lower Facelift (Jowl Lift)', 44),
    ('Mini Facelift', 45),
    ('One-Stitch Facelift', 46),
    ('Male Facelift', 47),
    ('Neck Lift', 48),
    ('Mini Neck Lift', 49),
    ('Male Neck Lift', 50),
    ('Chin & Neck Liposuction', 51),
    ('FaceTite', 52),
    ('Facial Fat Transfer', 53),
    ('Lip Lift', 54),
    ('Lip Reduction Surgery', 55),
    ('Buccal Fat Removal', 56),
    ('Dimple Creation', 57),
    ('Chin Surgery (Genioplasty)', 58),
    ('Chin Augmentation', 59),
    ('Chin Reduction', 60),
    ('Male Chin Surgery', 61),
    ('Liposuction', 62),
    ('Stomach Liposuction', 63),
    ('360 Liposuction', 64),
    ('Micro Liposuction (MicroLipo)', 65),
    ('High Definition Liposuction', 66),
    ('Abdominal Etching', 67),
    ('Male Liposuction', 68),
    ('BodyTite', 69),
    ('Cellulite Treatment', 70),
    ('Tummy Tuck (Abdominoplasty)', 71),
    ('Brazilian Tummy Tuck', 72),
    ('Mini Tummy Tuck', 73),
    ('Male Tummy Tuck', 74),
    ('Umbilicoplasty', 75),
    ('Mons Lift (Monsplasty)', 76),
    ('C-Section Scar Revision', 77),
    ('Body Contouring Procedures', 78),
    ('Fat Transfer (Fat Grafting)', 79),
    ('Pectoral Implants', 80),
    ('Chest Wall Implants', 81),
    ('Calf Augmentation with Implants', 82),
    ('Fat Transfer Calf Augmentation', 83),
    ('Brazilian Butt Lift (BBL)', 84),
    ('Ultrasound Guided BBL', 85),
    ('Skinny BBL', 86),
    ('Mini BBL', 87),
    ('360 Lipo and BBL', 88),
    ('Revision BBL', 89),
    ('Male BBL', 90),
    ('BBL Recovery Guide', 91),
    ('BBL Before & After', 92),
    ('Buttock Implants', 93),
    ('Butt Implant Removal', 94),
    ('Butt Implants vs BBL', 95),
    ('Non-Surgical Butt Lift (HyaCorp)', 96),
    ('Labiaplasty (Labia Reduction)', 97),
    ('Clitoral Hood Reduction', 98),
    ('Labiaplasty Revision', 99),
    ('Labia Puffing (Labial Puff)', 100),
    ('Vaginoplasty (Vaginal Tightening)', 101),
    ('Perineoplasty', 102),
    ('Pelvic Floor Repair', 103),
    ('Vaginal Rejuvenation', 104),
    ('IntimaLase Vaginal Tightening', 105),
    ('IncontiLase Urinary Incontinence', 106),
    ('ProlapLase Pelvic Prolapse', 107),
    ('RenovaLase Vaginal Dryness', 108),
    ('Non-Surgical Vaginal Tightening', 109),
    ('O-Shot Injection', 110),
    ('G-Spot Injection (G-Shot)', 111),
    ('Gynecomastia Surgery', 112),
    ('Male Breast Reduction', 113),
    ('Male Eyelid Surgery', 114),
    ('Male Body Lift', 115),
    ('Fotona 4D Laser Facelift', 116),
    ('SmoothEye Laser Treatment', 117),
    ('LipLase Lip Laser Treatment', 118),
    ('Erbium Laser Skin Resurfacing', 119),
    ('Laser TightSculpting', 120),
    ('Laser Skin Tightening', 121),
    ('Laser Acne Treatment', 122),
    ('Rosacea Laser Treatment', 123),
    ('Laser Cellulite Treatment', 124),
    ('Facial Thread Vein Removal', 125),
    ('Nose Thread Vein Removal', 126),
    ('Periorbital Vein Laser Treatment', 127),
    ('Veins Under the Eyes', 128),
    ('Venous Lake Removal', 129),
    ('Cherry Angioma Removal', 130),
    ('Laser Pigmentation Treatment', 131),
    ('Melasma Laser Treatment', 132),
    ('Age Spot Removal', 133),
    ('Laser Mole Removal', 134),
    ('Xanthelasma Removal', 135),
    ('Sebaceous Hyperplasia Removal', 136),
    ('Syringoma Removal', 137),
    ('Milia Removal', 138),
    ('Wart Removal', 139),
    ('Verruca Removal', 140),
    ('Seborrhoeic Keratosis Removal', 141),
    ('Dermatosis Papulosa Nigra Removal', 142),
    ('Actinic Keratosis Treatment', 143),
    ('Laser Scar Removal', 144),
    ('LineLase Stretch Mark Removal', 145),
    ('Laser Fungal Nail Treatment', 146),
    ('NightLase Snoring Treatment', 147),
    ('Vaginal Laser Treatment', 148),
    ('Laser Intimate Whitening', 149),
    ('Anti-Wrinkle Injections', 150),
    ('Frown Lines', 151),
    ('Forehead Wrinkles', 152),
    ('Crow''s Feet', 153),
    ('Bunny Lines', 154),
    ('Lip Flip', 155),
    ('Gummy Smile', 156),
    ('Jaw Slimming Injections', 157),
    ('Anti-Sweat Injections', 158),
    ('Muscle Relaxant for Migraine', 159),
    ('Dermal Fillers', 160),
    ('Facial Fillers', 161),
    ('Lip Fillers', 162),
    ('Cheek Fillers', 163),
    ('Nasolabial Folds', 164),
    ('Marionette Lines', 165),
    ('Chin Fillers', 166),
    ('Jawline Fillers', 167),
    ('Temple Filler', 168),
    ('Tear Trough Filler', 169),
    ('Non-Surgical Rhinoplasty', 170),
    ('Liquid Facelift (8-Point Lift)', 171),
    ('Filler Dissolving Treatment', 172),
    ('Morpheus8 RF Microneedling', 173),
    ('Skin Boosters', 174),
    ('Profhilo Treatment', 175),
    ('Thread Lift', 176),
    ('Double Chin Injections', 177),
    ('Skin Lesion Removal', 178),
    ('Facial Skin Lesion Removal', 179),
    ('Lip Lesion Removal', 180),
    ('Skin Tag Removal', 181),
    ('Mole Removal Surgery', 182),
    ('Cyst Removal Surgery', 183),
    ('Lipoma Removal Surgery', 184),
    ('Dermatofibroma Removal', 185),
    ('Pyogenic Granuloma Removal', 186),
    ('Osteoma Removal', 187),
    ('Rhinophyma Surgery', 188),
    ('Skin Cancer Surgery', 189),
    ('Scar Revision Surgery', 190),
    ('Facial Scar Revision', 191),
    ('Acne Scar Removal', 192),
    ('Hypertrophic Scar Treatment', 193),
    ('Keloid Scar Treatment', 194),
    ('Burn Scars Treatment', 195),
    ('Surgical Tattoo Removal', 196),
    ('Micro & Nano Fat Grafting', 197),
    ('Subcision for Cellulite', 198),
    ('Suction Curettage for Hyperhidrosis', 199),
    ('Blepharoplasty (Eyelid Surgery)', 200),
    ('Upper Eyelid Surgery', 201),
    ('Lower Eyelid Surgery', 202),
    ('Asian Blepharoplasty', 203),
    ('Canthoplasty (Almond Eye Surgery)', 204),
    ('Revision Blepharoplasty', 205),
    ('Brow Lift (Forehead Lift)', 206),
    ('Endoscopic Brow Lift', 207),
    ('Temporal Brow Lift', 208),
    ('Brow Lift vs Blepharoplasty', 209),
    ('Hairline Lowering', 210),
    ('AccuTite', 211),
    ('Otoplasty (Ear Pinning)', 212),
    ('Earlobe Repair', 213),
    ('Earlobe Reduction', 214),
    ('Body Contouring After Weight Loss', 215),
    ('Excess Skin Removal Surgery', 216),
    ('Extended Tummy Tuck', 217),
    ('Fleur-de-Lis Tummy Tuck', 218),
    ('Apronectomy (Panniculectomy)', 219),
    ('Arm Lift (Brachioplasty)', 220),
    ('Thigh Lift (Thigh Reduction)', 221),
    ('Lower Back Lift', 222),
    ('Bra Line Back Lift', 223),
    ('Buttock Lift (Gluteal Lift)', 224),
    ('Upper Body Lift', 225),
    ('Lower Body Lift', 226),
    ('Belt Lipectomy', 227),
    ('FtM / FtN Top Surgery', 228),
    ('Double Incision Top Surgery', 229),
    ('Keyhole Top Surgery', 230),
    ('MtF Top Surgery', 231),
    ('Facial Feminisation Surgery (FFS)', 232),
    ('Tracheal Shave', 233),
    ('Body Masculinisation Surgery', 234),
    ('Gender Affirmation Surgery', 235),
    ('WPATH Letter for Top Surgery', 236),
    ('FUE Hair Transplant', 237),
    ('Hairline Design & Lowering', 238),
    ('Crown & Vertex Restoration', 239),
    ('Beard Transplant', 240),
    ('Eyebrow Transplant', 241),
    ('Scar Hair Transplant', 242),
    ('PRP Hair Therapy', 243)
  )
  insert into public.procedures (
    normalized_key,
    display_name,
    is_active,
    sort_order,
    created_by
  )
  select
    public.normalize_master_key(display_name),
    public.normalize_master_display(display_name),
    true,
    sort_order,
    v_admin
  from source
  on conflict (normalized_key) do update
    set display_name = excluded.display_name,
        is_active = true,
        sort_order = excluded.sort_order,
        updated_at = now();

  insert into public.audit_logs (
    actor_user_id,
    action,
    entity_type,
    entity_id,
    metadata
  ) values (
    v_admin,
    'MASTER_CATALOGUE_IMPORTED',
    'procedures',
    null,
    jsonb_build_object(
      'source_url', 'https://pearls-demo-one.vercel.app/',
      'source_menu_entries', 263,
      'faq_entries_excluded', 8,
      'duplicate_entries_removed', 12,
      'unique_procedures_imported', 243,
      'new_procedures_created', 243 - v_existing_count,
      'existing_procedures_matched', v_existing_count
    )
  );
end
$$;

commit;

